# Generated by Django 5.1.4 on 2025-01-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="uploads/videos/")),
                ("location_longitude", models.FloatField()),
                ("location_latitude", models.FloatField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_frames_path", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
